### ISSUE TITLE
注释太少了

### ISSUE THREAD

**Issue by bluekiwier** [steponteam/FaceRecognization#1]
楼主代码的注释太少了

**Comment by sweetwxh** [comment]
额，还好吧，关键复杂的地方都加了注释。

**Comment by shuaqq2004** [comment]
确实是注释太少了。 我看懂了，是因为我同时还在看官方文档。

我看到注释和结构和我想象的有差距本来打算自己封装的一个的，把所有的C++类库、结构体、枚举值都p/invoke一份。然后忙其他项目去了，没时间。

其实可以看官方的中文文档和C++的头文件，很详细的注释。

建议：把官方所有的注释加入进来，会有更多人来用你的这套库。

**Comment by stepontech** [comment]
@shuaqq2004 其实封装的目的就是想屏蔽官方C++中相关的细节，对外暴露相对高层的调用函数，所以基本所有internal的类和结构体都没有加上注释，官方注释也比较详细。所有public的都尽量完善了注释，方便使用。如果是想看源码，可能要配合官方文档，只是使用的话，问题应该不大。

**Comment by sweetwxh** [comment]
已完善
