### ISSUE TITLE
Wrapper库包装的那部分代码是如何生成的

### ISSUE THREAD

**Issue by linsonxie** [steponteam/FaceRecognization#6]
若若的问下，Wrapper库包装的那部分代码是如何生成的，通过对C++sdk的接口研究然后手动自己写代码包装出来的吗，还是有什么工具可以做这件事情呢

**Comment by sweetwxh** [comment]
有两种方式，一种方式是根据C++的头文件来编写P/Invoke接口，这种方式你需要知道对应的类型在C#中用什么类型来表示，第二种方式是用生成工具来生成，https://github.com/mono/CppSharp
