### ISSUE TITLE
关于实时问题

### ISSUE THREAD

**Issue by andyhx** [steponteam/FaceRecognization#7]
请教一下您,
1.调用的是本地api吗,还是服务器的API,调用api时,人脸检测框会出现比较严重漂移现象吗,
2.多人脸识别支持吗,会延迟多久,感谢!

**Comment by sweetwxh** [comment]
1.本地API，基本还没有遇到过漂移现象。
2.支持多人脸，6000多人脸库大概1-2秒左右。
你可以直接跑DEMO测试一下。
